
export const INITIALIZED = 'INITIALIZED'
export const ROOT_CHANGED = 'ROOT_CHANGED'
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const FETCHING_REQUEST = 'FETCHING_REQUEST'
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS'
export const FETCHING_ERROR = 'FETCHING_ERROR'
export const INIT_DATA = 'INIT_DATA'
export const TOGGLE_VIEW_ALL_ISSUES = 'TOGGLE_VIEW_ALL_ISSUES'
export const SAVE_HRM_TOKEN = 'SAVE_HRM_TOKEN'
export const REMOVE_HRM_TOKEN = 'REMOVE_HRM_TOKEN'
export const SAVE_HRM_USER = 'SAVE_HRM_USER'

